export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER";
export const SAVE_QUESTION_ANSWER_SUCCESS = "SAVE_QUESTION_ANSWER_SUCCESS";
export const CLEAR_SAVED_QUESTION_ANSWER_SUCCESS =
  "CLEAR_SAVED_QUESTION_ANSWER_SUCCESS";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
